### ISSUE TITLE
ERROR: OpenSSL returned unexpected output when parsing APTicket.

### ISSUE THREAD

**Issue by albyvar** [axi0mX/apticket-nonce-checker#1]

**Comment by Danfrid** [comment]
Mee too
What is mean?

**Comment by axi0mX** [comment]
Is it a .shsh file or apticket.der? 32-bit or 64-bit device?

Run and share the output:

openssl asn1parse -inform DER -in (your filename)

**Comment by albyvar** [comment]
Shsh file of iPad 2,5 iOS 9.3.4

**Comment by albyvar** [comment]
iMac-di-alby:~ alby$ openssl asn1parse -inform DER -in
asn1parse: Option -in needs a value
asn1parse: Use -help for summary.
iMac-di-alby:~ alby$

**Comment by Danfrid** [comment]
Oh, I have shsh file, but I downgraded now with alitek's tool, thanks for reply :)

**Comment by axi0mX** [comment]
@albyvar Github did not show the right command, because I used brackets in my comment. This is what you need to run:
openssl asn1parse -inform DER -in (your filename)

**Comment by albyvar** [comment]
iMac-di-alby:apticket-nonce-checker-master alby$ openssl asn1parse -inform DER -in blob.shsh
    0:d=0  hl=2 l= 112 cons: appl [ 2 ]        
    2:d=1  hl=2 l= 105 cons: appl [ 12 ]       
Error in encoding
140737215230912:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:crypto/asn1/asn1_lib.c:91:
iMac-di-alby:apticket-nonce-checker-master alby$

**Comment by axi0mX** [comment]
Odd. Can you comment and attach your blob to it? I'll investigate.

**Comment by albyvar** [comment]
https://drive.google.com/open?id=0B2NG4JdgjSB_ZTV3SUJWUXJuTlk Here you go, github won't let me upload shsh files directly

**Comment by axi0mX** [comment]
OK. It's from BEEHIND, which saves it in a different format. I updated my script so it would detect that and tell you what to do.

This is the new output:
$ ./apticket-nonce-checker.py BEEHIND_YOUR_ECID_iPad2,5_9.3.4_13G35.shsh
ERROR: This is a binary plist. Convert it to XML first.
This command works on macOS: plutil -convert xml1 BEEHIND_YOUR_ECID_iPad2,5_9.3.4_13G35.shsh

After converting the file, you'll see that it has a nonce:
$ ./apticket-nonce-checker.py BEEHIND_YOUR_ECID_iPad2,5_9.3.4_13G35.shsh 
Parsing APTicket from SHSH file.
APTicket has a nonce.
Nonce (hex dump): 91c72fec77fdde6ee0359943c7c132859353055a
Nonce length:     20 bytes

**Comment by albyvar** [comment]
Ok, thanks very much. So aren't usable for the re-restore right?

**Comment by axi0mX** [comment]
Right.

**Comment by albyvar** [comment]
Can 8.3 and 8.2 blobs be used in future?

**Comment by axi0mX** [comment]
If firmware decryption keys are released for your iPad, yes, you would be able to downgrade with Odysseus (if your iPad is jailbroken). There are no keys for S5L8942 devices at the moment, so that probably won't happen soon.

**Comment by albyvar** [comment]
:/ So sad, anyway thank you again

**Comment by 128keaton** [comment]
I have this issue too, but I don't think its a Beehind blob. I found this randomly in a VM I use for jailbreak stuff.

[2718446112203.shsh.zip](https://github.com/axi0mX/apticket-nonce-checker/files/914675/2718446112203.shsh.zip)

* I've tried converting it to an XML file, but it isn't one I don't think


` openssl asn1parse -inform DER -in /Users/keatonburleson/Downloads/2718446112203.shsh`

`
    0:d=0  hl=4 l=   0 prim: <ASN1 1416>
    4:d=0  hl=2 l=   0 prim: EOC
`
